FROM node:18-alpine

WORKDIR /app

# Set default environment variable for build
ENV API_URL=http://api:8000

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the app in development mode
CMD ["npm", "run", "dev"] 